import turtle
t = turtle.Turtle()
turtle.bgcolor("black")
screen = turtle.Screen()
t.pensize(4)
t.pencolor("white")
graphic_size = 55
number_of_patterns = 10
t.penup()
t.forward(graphic_size)
t.left(360 / number_of_patterns)
t.pendown()
for i in range(number_of_patterns):
    t.forward(graphic_size)
    t.left(45 - (360 / (2 * number_of_patterns)))
    t.forward(graphic_size)
    t.right(90)
    t.forward(graphic_size)
    t.pencolor("red")
    t.circle(graphic_size, 90)
    t.left(90)
    t.circle(graphic_size, 90)
    t.pencolor("white")
    t.forward(graphic_size)
    t.right(90)
    t.forward(graphic_size)
    t.left(45 - (360 / (2 * number_of_patterns)))
    t.forward(graphic_size)
    t.right(180 - (720 / number_of_patterns))
t.hideturtle()
screen.exitonclick()
